name: API CI  # Ciclo de integración continuo de nuestra API

on:
  push:
    paths:
      - "api/**"
      - ".github/workflows/api-ci.yml"

defaults:
  run:
    working-directory: ./api  # Ajusta según dónde esté tu package.json

jobs:
  # ------------------------------
  # 1️⃣ Linter
  # ------------------------------
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm ci
      - run: npm run lint || true  # No falla si hay errores

  # ------------------------------
  # 2️⃣ Unit Tests
  # ------------------------------
  unit-test:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm ci
      - run: npm run test

  # ------------------------------
  # 3️⃣ E2E Tests (MongoDB 6.0)
  # ------------------------------
  e2e:
    runs-on: ubuntu-latest
    container:
      image: node:20
    services:
      mongo-e2e:
        image: mongo:6.0
        env:
          MONGO_INITDB_ROOT_USERNAME: test
          MONGO_INITDB_ROOT_PASSWORD: test123
          MONGO_INITDB_DATABASE: demo_e2e
        # Puerto interno del contenedor
        ports:
          - 27018:27017
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install dependencies
        run: npm ci
      - name: Run E2E tests
        env:
          MONGO_DB_NAME: demo_e2e
          # Desde GH Actions, el puerto interno sigue siendo 27017
          MONGO_URL: mongodb://test:test123@mongo-e2e:27017?retryWrites=true&writeConcern=majority
        run: npm run test:E2E
