name: API CI

on:
  push:
    paths:
      - "api/**"
      - ".github/workflows/api-ci.yml"

defaults:
  run:
    working-directory: ./api

jobs:
  # 1️⃣ Linter
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm ci
      - run: npm run lint || true

  # 2️⃣ Unit Tests
  unit-test:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm ci
      - run: npm run test

  # 3️⃣ E2E Tests con MongoDB 6.0
  e2e:
    runs-on: ubuntu-latest
    needs: unit-test
    services:
      mongo:
        image: mongo:6.0
        env:
          MONGO_INITDB_ROOT_USERNAME: test
          MONGO_INITDB_ROOT_PASSWORD: test123
          MONGO_INITDB_DATABASE: demo_e2e
        options: >-
          --health-cmd "mongo --eval 'db.adminCommand(\"ping\")'" 
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm ci
      - name: Wait for MongoDB to be ready
        run: |
          echo "Waiting for MongoDB..."
          for i in {1..15}; do
            mongo mongo:27017 -u test -p test123 --authenticationDatabase admin --eval "db.stats()" && break
            echo "Mongo not ready yet..."
            sleep 5
          done
      - name: Run E2E Tests
        env:
          MONGO_DB_NAME: demo_e2e
          MONGO_URL: mongodb://test:test123@mongo:27017?retryWrites=true&writeConcern=majority
        run: npm run test:E2E
